"""initialize tables

Revision ID: 13b64f818516
Revises: 
Create Date: 2026-01-26 08:37:02.030507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes



# revision identifiers, used by Alembic.
revision: str = '13b64f818516'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('middle_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mobile_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('street_1', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('street_2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('house_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('purok', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('barangay', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('zip_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('date_of_death', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'UNKNOWN', name='persongender'), nullable=False),
    sa.Column('father_id', sa.Integer(), nullable=True),
    sa.Column('mother_id', sa.Integer(), nullable=True),
    sa.Column('spouse_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['father_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['mother_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['spouse_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.create_index('ix_person_address', ['street_1', 'street_2', 'house_number', 'purok', 'barangay', 'city', 'state', 'zip_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_mobile_number'), ['mobile_number'], unique=False)
        batch_op.create_index('ix_person_name', ['first_name', 'middle_name', 'last_name'], unique=False)

    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('min_seat', sa.Integer(), nullable=False),
    sa.Column('max_seat', sa.Integer(), nullable=False),
    sa.Column('sort_index', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_position_code'), ['code'], unique=True)

    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_code'), ['code'], unique=True)

    op.create_table('partylist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partylist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partylist_name'), ['name'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_account', ['name', 'email'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_name'), ['name'], unique=True)

    op.create_table('audit',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='auditaction'), nullable=False),
    sa.Column('log', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit', schema=None) as batch_op:
        batch_op.create_index('ix_audit_type_action', ['type', 'action'], unique=False)

    op.create_table('candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('middle_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('partylist_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('balot_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partylist_id'], ['partylist.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_alias'), ['alias'], unique=False)
        batch_op.create_index('ix_candidate_name', ['first_name', 'middle_name', 'last_name'], unique=False)

    op.create_table('voter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voter_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('precinct_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('surveyor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['surveyor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voter_voter_no'), ['voter_no'], unique=True)

    op.create_table('votercandidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['voter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votercandidate')
    with op.batch_alter_table('voter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voter_voter_no'))

    op.drop_table('voter')
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_index('ix_candidate_name')
        batch_op.drop_index(batch_op.f('ix_candidate_alias'))

    op.drop_table('candidate')
    with op.batch_alter_table('audit', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_type_action')

    op.drop_table('audit')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_name'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index('ix_user_account')

    op.drop_table('user')
    with op.batch_alter_table('partylist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partylist_name'))

    op.drop_table('partylist')
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_code'))

    op.drop_table('role')
    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_position_code'))

    op.drop_table('position')
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_index('ix_person_name')
        batch_op.drop_index(batch_op.f('ix_person_mobile_number'))
        batch_op.drop_index(batch_op.f('ix_person_email'))
        batch_op.drop_index('ix_person_address')

    op.drop_table('person')
    # ### end Alembic commands ###
