export enum Position {
  President = "president",
  VicePresident = "vice-president",
  Senator = "senator",
  HouseOfRepresentatives = "house-of-representatives",
  ProvincialGovernor = "provincial-governor",
  ProvincialViceGovernor = "provincial-vice-governor",
  SangguniangPanlalawigan = "sangguniang-panlalawigan",
  Mayor = "mayor",
  ViceMayor = "vice-mayor",
  SangguniangPanlungsod = "sangguniang-panlungsod",
  SangguniangBayan = "sangguniang-bayan",
  BarangayCaptain = "barangay-captain",
  BarangayKagawad = "barangay-kagawad",
  SangguniangKabataan = "sangguniang-kabataan",
  Other = "other",
}
